Insert into `RESTAURANT` values 
("Chili's","Phoenix Mall, Chennai","+91 1449027569");
insert into `MANAGER` values
("Shreyans", "9827469182", "Delhi Nagar 51", “20000”),
("Megha", "9273648102", "Mysore Road, Nagaland", “25000”);
insert into `WAITER` values
("Ayan", "8892789078", “18000”),
("Gudiya", "7789092345", “15000”),
("Anita", "6678944566", “17000”),
("Homie", "9944558765", “12000”);
insert into `CASHIER` values
("Abhinav", "9435778823", “19000”);
insert into `CHEF' values
("Gordon", "1190982736", "Imperial Road", “27000”),
("Jamie", "9946372837", "Burma Nagar", “25000”),
("Mulan", "9989172837", "Stremer Colony", “20000”);

insert into `Menu` values
("Chicken Momos", "Steamed", "5 Nos", "80"),
("Chicken Momos", "Fried", "5 Nos", "90"),
("Chicken Garlic Momos", "Chinese/Fried", "5 Nos", "110"),
("Pork Ribs", "Continental", "4 Nos", "500"),
("French Fries", "Fast Food", "1 Plate", "80"),
("Spaghetti", "Italian", "1 Plate", "350"),
("Non-Veg Platter", "Combo", "1 Huge Plate", "800");

